# Generated by Django 4.1.7 on 2023-04-24 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_sos2_ca_sos2_fp_sos2_sn_sos2_ws_alter_sos2_la'),
    ]

    operations = [
        migrations.CreateModel(
            name='so1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('La', models.CharField(max_length=100)),
                ('Fp', models.CharField(default='', max_length=100)),
                ('Sn', models.CharField(default='', max_length=100)),
                ('Ws', models.CharField(default='', max_length=100)),
                ('Ca', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
